name: M3U generator

on:
  schedule:
    - cron: '0 */3 * * *'   # corre cada 3 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Config git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install requests yt-dlp

      - name: Run grabber
        run: python3 scripts/youtube_m3ugrabber.py

      - name: Commit & push
        run: |
          git add youtube.m3u
          git commit -m "links are updated" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

