name: M3U generator

on:
  schedule:
    - cron: '0 */3 * * *'   # corre cada 3 horas
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # habilita permisos de escritura en el repo

    steps:
      - uses: actions/checkout@v4

      - name: Config git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install requests yt-dlp

      - name: Run autorun.sh
        run: |
          chmod +x autorun.sh
          ./autorun.sh

      - name: Commit & push
        run: |
          git add -A
          git commit -m "links are updated" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

